### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by manoochehri** [openx/OX3-Python-API-Client#28]
What is the license used for OX3-Python-API-Client? MIT? BSD?

**Comment by manoochehri** [comment]
BSD License was removed at this commit: https://github.com/openx/OX3-Python-API-Client/commit/f2fa5b9841f9e855fb7f8b36cfedf5e688f0e22e

**Comment by flaker** [comment]
@manoochehri I had to revert a change for other reasons and the license was removed at that point. It will be added back. Sorry for the confusion.

**Comment by manoochehri** [comment]
Thanks for responding. I'll track this to watch for the change.

**Comment by openx-luis** [comment]
License is back: 
* https://github.com/openx/OX3-Python-API-Client/blob/develop/LICENSE.txt
