### ISSUE TITLE
ConfigParser in python3

### ISSUE THREAD

**Issue by oluaPt** [openx/OX3-Python-API-Client#35]
Hey, i have this error:

import ox3apiclient # https://docs.openx.com/Content/developers/platform_api/about_topics_api.html
  File "/usr/local/lib/python3.5/dist-packages/ox3apiclient/__init__.py", line 3, in <module>
    import ConfigParser
ImportError: No module named 'ConfigParser'

**Comment by emilyzzz** [comment]
Hi @oluaPt, maybe it's PYTHONPATH issue, please make sure the path "ConfigParser" is installed is in PYTHONPATH.  

I just had similar issue, for me it's "No module named requests_oauthlib". I fixed it by:
1)  in python terminal,  import sys, sys.path,  to find what's in the path
2)  open ~/.bash_profile, added line "export PYTHONPATH="${PYTHONPATH}:/usr/local/lib/python2.7/site-packages",   then "source ~/.bash_profile". 
3) go back to python terminal, try import ox3apiclient again. For me it worked after PYTHONPATH fixed.

**Comment by flaker** [comment]
@oluaPt 

You seem to be using Python 3.X. That version of Python does not have the module ConfigParser.
The develop branch already supports Python 3 by using Six. I hope it will be the master branch soon.

**Comment by oluaPt** [comment]
Hey, ty for the reply.

The issue here is that im using py3 and the module ConfigParser in py3 its configparser (without camel case), and thats the issue

**Comment by flaker** [comment]
@oluaPt yep. As soon as develop hits master and pypi it will be Python 2 and 3 compatible. If you use master today there are a couple of places you'll need to make fixes.

**Comment by oluaPt** [comment]
ok, any ideia when it will be on master? ty for the reply

**Comment by flaker** [comment]
hopefully soon... but it's not up to me. So I am just guessing :)

**Comment by oluaPt** [comment]
Ok, im going to close the issue, ty for the help =)

**Comment by flaker** [comment]
@oluaPt 
current Pypi version is Python 3 compatible (also develop and master were updated)
